# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Insiders' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Insiders
  pod 'SwiftLint'

  pod 'Cartography', '~> 4.0.0'

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

end
